/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    HomeHeroVisualPanel: typeof import('./components/home/HomeHeroVisualPanel.vue')['default']
    HomeNovaHero: typeof import('./components/home/HomeNovaHero.vue')['default']
    HomeWelcomeHero: typeof import('./components/home/HomeWelcomeHero.vue')['default']
    NovaArticlesFeed: typeof import('./components/nova/NovaArticlesFeed.vue')['default']
    NovaBookmarkPoolIcon: typeof import('./components/nova/NovaBookmarkPoolIcon.vue')['default']
    NovaProjectPoolIcon: typeof import('./components/nova/NovaProjectPoolIcon.vue')['default']
    NovaProjectsShowcase: typeof import('./components/nova/NovaProjectsShowcase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
